# ---------------------------------------------------------------------------- #
#                                   Variables                                  #
# ---------------------------------------------------------------------------- #
include Makefile.cfg

# Virgule litterale : sans elle, -fsanitize=a,b casse la macro $(if ...).
, := ,

# ----------------------------------- Tools ---------------------------------- #
MKDIR				:= mkdir
RM					:= rm

CXX					:= g++
CLANG_FORMAT		:= clang-format

CXXWARN				:= all extra error
CXXWARN				:= $(CXXWARN:%=-W%)

CXXFLAGS			:= -std=c++20 -MMD -MP $(CXXWARN) \
	$(if $(OPTIMIZE),-O3 -DNDEBUG,) \
	$(if $(NATIVE),-march=native,) \
	$(if $(DEBUG),-g3 -O0,) \
	$(if $(SANITIZE),-fsanitize=address$(,)undefined -fno-omit-frame-pointer,) \
	$(CXXMOREFLAGS)

LD					:= $(CXX)
LDFLAGS				:= -pthread \
	$(if $(SANITIZE),-fsanitize=address$(,)undefined,) \
	$(LDMOREFLAGS)

# --------------------------------- Profile ---------------------------------- #
# Affiche a chaque edition de liens : on sait toujours quel binaire on tient.
PROFILE				:= $(if $(DEBUG),debug,release)$(if $(SANITIZE), +asan/ubsan,)$(if $(NATIVE), +native,)

# ---------------------------------- Output ---------------------------------- #
# Le sujet impose un executable nomme `Gomoku` a la racine du depot.
NAME				:= Gomoku
TEST_NAME			:= gomoku_tests
BENCH_NAME			:= gomoku_bench

NAME_PATH			:= $(OUTDIR)/$(NAME)
TEST_PATH			:= $(OUTDIR)/$(TEST_NAME)
BENCH_PATH			:= $(OUTDIR)/$(BENCH_NAME)

# ---------------------------------- Sources --------------------------------- #
# Ajouter une couche = ajouter une ligne ici.
SRCDIR				:= src
INCDIR				:= include
TESTDIR				:= tests
BENCHDIR			:= bench

CXXFLAGS			+= -I$(INCDIR)

SRCS_CORE			:= $(wildcard $(SRCDIR)/core/*.cpp) \
					$(wildcard $(SRCDIR)/eval/*.cpp) \
					$(wildcard $(SRCDIR)/search/*.cpp) \
					$(wildcard $(SRCDIR)/game/*.cpp) \
					$(wildcard $(SRCDIR)/net/*.cpp) \
					$(wildcard $(SRCDIR)/server/*.cpp)

SRCS_MAIN			:= $(wildcard $(SRCDIR)/main.cpp)
SRCS_TEST			:= $(wildcard $(TESTDIR)/*.cpp)
SRCS_BENCH			:= $(wildcard $(BENCHDIR)/*.cpp)

OBJS_CORE			:= $(SRCS_CORE:%.cpp=$(OBJDIR)/%.cpp.o)
OBJS_MAIN			:= $(SRCS_MAIN:%.cpp=$(OBJDIR)/%.cpp.o)
OBJS_TEST			:= $(SRCS_TEST:%.cpp=$(OBJDIR)/%.cpp.o)
OBJS_BENCH			:= $(SRCS_BENCH:%.cpp=$(OBJDIR)/%.cpp.o)

DEPS				:= $(OBJS_CORE:%.cpp.o=%.cpp.d) \
					$(OBJS_MAIN:%.cpp.o=%.cpp.d) \
					$(OBJS_TEST:%.cpp.o=%.cpp.d) \
					$(OBJS_BENCH:%.cpp.o=%.cpp.d)

FMT_FILES			:= $(shell find $(SRCDIR) $(INCDIR) $(TESTDIR) $(BENCHDIR) \
					\( -name '*.cpp' -o -name '*.hpp' \) 2>/dev/null)